### PR TITLE
feat: add sell_all for route executor

### PR DESCRIPTION
**Pull request by dmoka**
Fixes https://github.com/galacticcouncil/hydration-node/issues/883

- [x] test out on chopsticks

### CODE REVIEW

**Review by mrq1911 — CHANGES_REQUESTED** [review]
benchmarks

**Review by mrq1911 — APPROVED** [review]
bechmark is not necessary as there is no additional read

**Review by jak-pan — APPROVED** [review]
I assume the native balance test is also a fee payment asset and in this case LGTM

**Comment by dmoka** [comment]
> I assume the native balance test is also a fee payment asset and in this case LGTM

@jak-pan  Although it is true that the fee payment asset is indeed HDX in the native balance test, it does not have any impact as in integration tests the tx fees are not deducted directly. Anyway, I tested out sell_all on chopsticks, and working fine, first the fee is deducated then the rest is sold in `sell_all`

**Comment by dmoka** [comment]
https://github.com/galacticcouncil/hydration-ui/pull/1042

**Pull request merged**
